Step towards automation
openmainframeproject/cobol-check pull request #159
Opened 2021-11-23 13:46 UTC by dakaa16

The following changes are a suggestion on how to automate pull requests, and thus minimizing management time, and approval time for pull requests.

A GitHub Action has been set up to run tests and approvalTests when pushing a branch. Note; currently any pushed branch will start this Action. Tests will run on Ubuntu 18.04, Windows Server 2019 and macOS 10.15, all on both JDK 8 and 11.

Some tests have been corrected, in order for all tests to succeed on all above mentioned platforms and Java versions.

2021-11-24 08:36 UTC, Rune-Christensen commented on gradle.properties
> +artifactory_url = https://artifactory.tools.bdpnet.dk/artifactory
This line is wrong, points to internal artifactory.

2021-11-24 08:37 UTC, Rune-Christensen commented on gradle.properties
> +systemProp.sonar.host.url=http://sonar.devops.bdpnet.dk
This line is wrong, points to internal sonarqube

2021-11-24 08:38 UTC, Rune-Christensen requested changes
gradle.properties should not point to internal products. 
This should be fixed before merge.

2021-11-25 07:20 UTC, dakaa16 commented
@Rune-Christensen somehow the code you are referencing got included in an attempt to sign off a commit. I'll be deleting this pull request and create a new one.

2021-11-25 07:21 UTC, closed without merging