Sign off
openmainframeproject/cobol-check pull request #263
Opened 2022-11-15 17:59 UTC by sam94dion

Signed-off-by: Samuel <sam94dion@gmail.com>

2022-11-15 18:02 UTC, sam94dion commented
Hi,

So I did a rebase to avoid signing of all my previous commits. Sorry If that is not the best way. Doing a rebase is what I found on stackoverflow.

Added functionalities :

1. If you want to test a subprogram but the sub program is passed a linkage section you would want to stub that part for the program to be able to run without dependences.

example:

```
 LINKAGE SECTION.  
 COPY COPY002.
 PROCEDURE DIVISION.
```


TO 

```
      * LINKAGE SECTION.
       
       COPY COPY002.

       PROCEDURE DIVISION.
```

2. You might declare SQL cursors within your working-section which will need to be stubbed

example:

```
           EXEC SQL  
              DECLARE NAME-CUR CURSOR FOR  
              SELECT FIRST_NAME, LAST_NAME FROM TEXEM
           END-EXEC.
```

TO

```
      *      EXEC SQL  
      *        DECLARE NAME-CUR CURSOR FOR  
      *        SELECT FIRST_NAME, LAST_NAME FROM TEXEM
      *      END-EXEC.
```
3. If you have SQL copybook you might want to use the variables within the copybook but discard other information.
example:

```
       EXEC SQL INCLUDE TEXEM  END-EXEC.
```

TO

```
       01  TEXEM.                                                               
           10 FIRST-NAME           PIC X(10).                                   
           10 LAST-NAME            PIC X(10).                                   
           10 TMS-CREA             PIC X(26).     
```

2022-11-16 03:32 UTC, sam94dion commented
@dakaa16 

I didn't want to make a instant of reader in the generate class to use readAsOneStatement() that is why I created the getter()

2023-01-02 12:17 UTC, dakaa16 requested changes
Hi @sam94dion  - Happy new year! :D
There are some minor issues, that I would like you to fix. In addition to that, please do not touch the zip files, as they are the different distribution versions, that are meant for the public to download. These should not be deleted, and a new version should only be added, when a new release is planned.

I apologize for any inconvenience the late reply might cause, and I hope that you are still interested in helping us getting you changes into the next release of cobol check.

2023-01-05 22:06 UTC, sam94dion commented
Hi @dakaa16 I'll get those fixed in a bit :)

2023-01-09 19:23 UTC, sam94dion commented on .gitignore
> +default.conf
This file is the default.conf that you need to run gnu Cobol. I could take it out and add it in my environment variables

2023-01-09 19:40 UTC, sam94dion commented on src/main/java/org/openmainframeproject/cobolcheck/features/interpreter/CopybookExpander.java
> + * In the general use case, COPY statements are left alone and the compiler
fixed

2023-01-09 19:40 UTC, sam94dion commented on cobolcheck.cmd
> +java -jar bin\cobol-check-0.2.4.jar %*
fixed

2023-01-09 19:41 UTC, sam94dion commented on .gitignore
> +default.conf
I left it there please tell me if this is a problem

2023-01-09 19:42 UTC, sam94dion commented
Done should be better :)

2023-08-17 06:41 UTC, Rune-Christensen commented
Hi @sam94dion 
These changes were implemented in pull request https://github.com/openmainframeproject/cobol-check/pull/278 
I am therefore closing this PR.
Thank you :-)

2023-08-17 06:41 UTC, closed without merging