Extension Config can now take absolute path
openmainframeproject/cobol-check pull request #328
Opened 2023-10-19 08:29 UTC by oakmount66

2023-10-19 08:50 UTC, Rune-Christensen requested changes

2023-10-19 08:50 UTC, Rune-Christensen commented on vs-code-extension/Cobol-check/config.properties
config.properties in COBOL-Check root should reflect this change.

2023-10-19 08:50 UTC, Rune-Christensen commented on scripts/windows_gnucobol_run_tests.cmd
I do not think this should be deleted, they are referred in the config.properties file in COBOL Check root

2023-10-19 08:50 UTC, Rune-Christensen commented on scripts/linux_gnucobol_run_tests
I do not think this should be deleted, they are referred in the config.properties file in COBOL Check root

2023-10-19 08:50 UTC, Rune-Christensen commented on vs-code-extension/Cobol-check/scripts/linux_gnucobol_run_tests
This comparison bugs me.
When looking in the developer branch, the file does not look like this, originally.
Both this and the windows cmd files, where changed to run cobc -xj in a previous PR...

2023-10-19 08:50 UTC, Rune-Christensen commented on vs-code-extension/Cobol-check/scripts/windows_gnucobol_run_tests.cmd
is there a reason that %~n1 is moved to a new line?

2023-10-20 06:29 UTC, oakmount66 commented on vs-code-extension/Cobol-check/scripts/linux_gnucobol_run_tests
Changed back

2023-10-20 06:29 UTC, oakmount66 commented on vs-code-extension/Cobol-check/scripts/windows_gnucobol_run_tests.cmd
Clean Code. Instead of doing several commands in one line divided by && I prefer separate lines.

2023-10-20 06:31 UTC, oakmount66 commented on scripts/windows_gnucobol_run_tests.cmd
It has been moved to ./vs-code-extension/Cobol-check/scripts library

2023-10-20 06:31 UTC, oakmount66 commented on scripts/linux_gnucobol_run_tests
It has been moved to ./vs-code-extension/Cobol-check/scripts library

2023-10-20 06:32 UTC, oakmount66 commented on vs-code-extension/Cobol-check/config.properties
I think it does. Comments and samples in line 53 to 61 has been added.

2023-10-20 06:39 UTC, Rune-Christensen requested changes

2023-10-20 06:39 UTC, Rune-Christensen commented on vs-code-extension/Cobol-check/default.properties
>  cobolcheck.test.program.path = Cobol-check
This is the default setup, then the path should be ./ and not Cobol-check

2023-10-20 06:44 UTC, Rune-Christensen approved these changes

2023-10-20 10:43 UTC, Rune-Christensen approved these changes

2023-10-23 10:21 UTC, Rune-Christensen commented
We know that approval tests are failing, we have realised that these have failed for a while, so we are not going to let that stop these changes.
We will look into fixing the approval tests soon.

2023-10-23 10:22 UTC, merged